apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-operator
  namespace: application-operator-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      name: application-operator
  template:
    metadata:
      labels:
        name: application-operator
    spec:
      serviceAccountName: application-operator
      containers:
        - name: application-operator
          # Replace this with the built image name
          image: 946899997174.dkr.ecr.us-east-1.amazonaws.com/application-operator
          command:
          - application-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "application-operator"
